### ISSUE TITLE
Implement latitude-longitude box

### ISSUE THREAD

**Issue by negillett** [os-climate/physrisk-ui#10]
We'd like users to have the option of selecting event position by providing plaintext lat/lon.
This issue is for implementing the text box in the UI for input and a button to submit the request to the API's hazard route implemented by https://github.com/os-climate/physrisk-api/issues/5.
As is with #11, graphed intensity curve(s) from the response should be displayed below the map box.

**Comment by deepanshu44** [comment]
Hello @negillett , I want to ask whether public contributions are allowed on this repo. 
I would like to read the codebase and may be contribute.

**Comment by negillett** [comment]
Hi, @deepanshu44! I believe the answer is "yes" but I'll pass to @HeatherAck.

**Comment by HeatherAck** [comment]
Hi @deepanshu44 - yes, our repos are now open to contributions from the public.  Please feel free to let us know if you have any questions.  We have a weekly Physical Risk-related tech meeting on Thursdays at - you can also find more info about OS-Climate here:  https://github.com/os-climate/OS-Climate-Community-Hub#readme

**Comment by deepanshu44** [comment]
Thanks @HeatherAck 

@negillett  , if I have understood correctly, we need to create a textbox where a user can enter lat/lon.

Clicking on submit button will select the location on the map and send a request to server and then a graph will be displayed based on the response object.

And where should be this input box positioned in the UI?

**Comment by negillett** [comment]
@deepanshu44, that was never really decided so I think we're open to wherever seems to make the most sense from a user perspective. If you'd like to take this issue, could you attach a screen shot to the PR? We can then make positioning of this feature part of the review process.

**Comment by deepanshu44** [comment]
@negillett , I've sent a pull request. I believe I've understood the requirement correctly?

**Comment by joemoorhouse** [comment]
Hi (and welcome!) @deepanshu44 and @negillett,

That indeed looks like what we had in mind. I think having it in the top right works well. The hazard viewer (in contrast to other screens) is based around a *single* location - we can click on the map to drop a location and then see the hazards for that location. The lat/lon box should be another way to select the location. So probably we want to drop / move the marker exactly as if we had clicked on the map on entering the data. 
One desirable future extension would be to give ability to add an address / postcode and perform geolocation, so having a box that can accept text in a flexible way might be a good option, e.g. '51.7, -1.26' (a la Google Maps for example), as opposed to a lat/lon specific one? Then this looks more like a generic search box?

In terms of styling etc, we are using MUI https://mui.com/. From a quick look there is this component which might work well?  
https://mui.com/material-ui/react-text-field/

But flexibility here to try something out and see how it works: these are just ideas...

Cheers,
Joe

**Comment by negillett** [comment]
@deepanshu44, @joemoorhouse, yeah position looks good and I agree that entering coordinates should place the marker on the map as if clicked.

**Comment by deepanshu44** [comment]
@negillett Will code formatter (eg Prettier) will be added to the project, 
 as my local settings are reformatting the code base.

**Comment by negillett** [comment]
@deepanshu44, no plans as of yet but it's something I think this project should have. We use auto formatting tools in the Python repos but I'm not familiar with what's available for JS. @joemoorhouse, @Floflow any thoughts?

**Comment by joemoorhouse** [comment]
Hi @deepanshu44, @negillett. Yes let's do this. Prettier seems a popular choice in JS, so very happy to go with that. On the Python side we have consolidated running of tests and auto-formatting (using tox) which is nice. We run that locally and in GitHub Actions. I was wondering how best to do the same thing in the JS world. 

From a quick look around I liked the approach here
https://blog.logrocket.com/using-prettier-eslint-automate-formatting-fixing-javascript/
where we could run:
npm test
npm run format
by adding extra scripts into package.json to make npm run format work (see article)

We can then run that locally via command line and in Actions (presumably we also want to add to IDE).

Does that seem ok, or any better approaches? (possibly checking with any experts we know?). Otherwise, from a first look defining the script in package.json seems reasonable.

**Comment by deepanshu44** [comment]
@negillett if you don't mind, can I create an issue for this? 

I have one more question, does this project also targets mobile devices?
As right now, in my mobile,  UI appears just for a split second and then disappears? 
If it is then, this bug needs to be debugged but later.

**Comment by negillett** [comment]
By all means, @deepanshu44! And yes, we do eventually need mobile compatibility.

**Comment by joemoorhouse** [comment]
Yes indeed I can view the sandbox on my phones OK (personal Android, work iPhone) 
http://physrisk-ui-latest-sandbox.apps.odh-cl1.apps.os-climate.org/
but great to debug issues on mobile devices. Very useful as a show-and-tell tool.
There is a bug I know about that is swallowed on desktop but which I wonder if causes issues elsewhere...

**Comment by joemoorhouse** [comment]
By the way, @deepanshu44, on the project we have a number of drop-in 'office hours' sessions on Teams. No obligation at all, but just an opportunity for face-to-face time. If of interest, please send me your email (can send to joe.moorhoouse@gmail.com) and I'm happy to add you to the UI session.

**Comment by deepanshu44** [comment]
Thanks @joemoorhouse will surely do so.

And one more thing, 
In this particular issue are we required to do something like [this](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/) (try to input coordinates in the map, eg 50,50).

**Comment by joemoorhouse** [comment]
Hi @deepanshu44, yes exactly. I think we are far more looking for a search box for geo-coding.
