### ISSUE TITLE
Display loaded asset data in AssetViewer in data grid

### ISSUE THREAD

**Issue by joemoorhouse** [os-climate/physrisk-ui#29]
Identify suitable data grid. 

[MIT version has no virtualization: is there good free alternative?] 
https://mui.com/x/react-data-grid/

Map component may be the same one as HazardViewer, configured differently.

Probably both map component and grid displayed, selecting one asset highlights both.

**Comment by negillett** [comment]
@joemoorhouse could this be closed now that #33 is merged?
